# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build auto-abzar`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t auto-abzar`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system auto-abzar && \
          adduser --system -G auto-abzar auto-abzar

COPY dist/auto-abzar auto-abzar/
RUN chown -R auto-abzar:auto-abzar .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix auto-abzar --omit=dev -f install

CMD [ "node", "auto-abzar" ]
